const assembleTeam = myteam => {
// HTML template for manager card using bootstrap (basic cards)
// Manager with their name, role, id, email, and office number
    const htmlManager = manager => {
        return `
        <div class="card employee-card">
        <div class="card-header">
            <h2 class="card-title">${manager.getName()}</h2>
            <h3 class="card-title">${manager.getRole()}</h3>
        </div>
        <div class="card-body">
            <ul class="list-group">
                <li class="list-group-item">Employee ID: ${manager.getId()}</li>
                <li class="list-group-item">Email: <a href="mailto:${manager.getEmail()}">${manager.getEmail()}</a></li>
                <li class="list-group-item">Office Number: ${manager.getOfficeNumber()}</li>
            </ul>
        </div>
    </div>
        `;
    };
// HTML template for an intern card using bootstrap (basic cards)
// Intern with their name, role, id, email, and school

    const htmlIntern = intern => {
        return `
        <div class="card employee-card">
    <div class="card-header">
        <h2 class="card-title">${intern.getName()}</h2>
        <h3 class="card-title">${intern.getRole()}</h3>
    </div>
    <div class="card-body">
        <ul class="list-group">
            <li class="list-group-item">Employee ID: ${intern.getId()}</li>
            <li class="list-group-item">Email: <a href="mailto:${intern.getEmail()}">${intern.getEmail()}</a></li>
            <li class="list-group-item">School: ${intern.getSchool()}</li>
        </ul>
    </div>
</div>
        `;
    };

// HTML template for an engineer card using bootstrap (basic cards)
// Engineer with their name, role, id, email, and GitHub

    const htmlEngineer = engineer => {
        return `
        <div class="card employee-card">
    <div class="card-header">
        <h2 class="card-title">${engineer.getName()}</h2>
        <h3 class="card-title"></i>${engineer.getRole()}</h3>
    </div>
    <div class="card-body">
        <ul class="list-group">
            <li class="list-group-item">Employee ID: ${engineer.getId()}</li>
            <li class="list-group-item">Email: <a href="mailto:${engineer.getEmail()}">${engineer.getEmail()}</a></li>
            <li class="list-group-item">GitHub Username: <a href="https://github.com/${engineer.getGithub()}" target="_blank" rel="nogit">${engineer.getGithub()}</a></li>
        </ul>
    </div>
</div>
        `;
    };

const htmlDetails = [];

// Create HTML cards for each manager in the team and add them to the html array
htmlDetails.push(myteam.filter(employee => employee.getRole() === "Manager")
    .map(manager => htmlManager(manager))
);

// Create HTML cards for each engineer in the team, join them into a single string, and add it to the html array
htmlDetails.push(myteam.filter(employee => employee.getRole() === "Engineer")
    .map(engineer => htmlEngineer(engineer))
    .join("")
);

// Create HTML cards for each intern in the team, join them into a single string, and add it to the html array
htmlDetails.push(myteam.filter(employee => employee.getRole() === "Intern")
    .map(intern => htmlIntern(intern))
    .join("")
);

// joins all the HTML strings in the html array into a single HTML string and returns it
return htmlDetails.join("");
}
// Return the HTML string with the team members generated by the assembleTeam function.
module.exports = myteam => {
    return `
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> My Team </title>
    <!-- Import the Bootstrap CSS stylesheet -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Import a custom CSS stylesheet -->
    <link rel="stylesheet" href="style.css">
</head>

<body>
 <header class="text-center p-5 mb-3 bg-info">
        <h1 class="text-light display-3">My Team</h1>
</header>
<!-- Add a container to center the team member cards on the page -->
    <div class="container">
        <div class="row">
<!-- Use Bootstrap's justify-content-center class to center the team member cards horizontally -->
            <div class="justify-content-center team-area col-12 d-flex">
                ${assembleTeam(myteam)}
            </div>
        </div>
    </div>
</body>
</html>
    `;
};